apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

    # 특정 키 값 가져오기
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-config
          key: password

    # 모든 키 값 가져오기
    envFrom:
    - secretRef:
        name: secret-config

    # 볼륨 마운트해서 볼륨에 키 값 가져오기
    volumeMounts:
    - name: secret-volume
      mountPath: /config
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-config

  imagePullSecrets:
  - name: docker-pull-secret