# -*- mode: ruby -*-
# vi: set ft=ruby :
# DB -> Docker
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "docker" do |docker|
        docker.vm.hostname = "docker-Server"
        docker.vm.provider "virtualbox" do |vb|
            vb.name = "docker-Server"
            vb.cpus = 4
            vb.memory = 8192
        end
        docker.vm.network "private_network", ip: "192.168.10.20"
    end

end