# -*- mode: ruby -*-
# vi: set ft=ruby :
# DB 테스트
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "db" do |db|
        db.vm.hostname = "db-Server"
        db.vm.provider "virtualbox" do |vb|
            vb.name = "db-Server"
            vb.cpus = 8
            vb.memory = 8192
        end
        db.vm.network "private_network", ip: "192.168.10.10"
        db.vm.network "public_network"
        db.vm.provision "shell", inline: <<-SCRIPT
        SCRIPT
    end

end