# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "gw" do |gw|
    gw.vm.hostname = "gateway"
    gw.vm.provider "virtualbox" do |vb|
    vb.name = "gateway"
    vb.cpus = 2
    vb.memory = 2048
    end
    gw.vm.network "public_network"
    gw.vm.network "private_network", ip: "192.168.33.254"

    gw.vm.provision "shell", inline: <<-SCRIPT
    SCRIPT
  end

  config.vm.define "web1" do |web1|
    web1.vm.hostname = "web-server1"
    web1.vm.provider "virtualbox" do |vb|
    vb.name = "nginx-server"
    vb.cpus = 2
    vb.memory = 2048
    end
    web1.vm.network "private_network", ip: "192.168.33.10"


    web1.vm.provision "shell", inline: <<-SCRIPT
  SCRIPT
  end

  config.vm.define "web2" do |web2|
    web2.vm.hostname = "web-server2"
    web2.vm.provider "virtualbox" do |vb|
    vb.name = "apache-server"
    vb.cpus = 2
    vb.memory = 2048
    end
    web2.vm.network "private_network", ip: "192.168.33.20"

    web2.vm.provision "shell", inline: <<-SCRIPT
    SCRIPT
  end

end
