# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "dock" do |dock|
        dock.vm.hostname = "docker"
        dock.vm.provider "virtualbox" do |vb|
            vb.name = "docker"
            vb.cpus = 4
            vb.memory = 8192
        end
        dock.vm.network "private_network", ip: "192.168.10.12"
        dock.vm.network "public_network"
        dock.vm.provision "shell", inline: <<-SCRIPT
        sudo apt-get update -y
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update -y
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo usermod -aG docker $USER
        docker login -u jochanho --password-stdin < /vagrant/env/docker_token
        git clone https://github.com/devlukej/project.git
        docker run --name jenkins-docker -itd -p 8080:8080 -p 50000:50000 --restart=always -v /home/jenkins:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker --group-add 998 -u root jenkins/jenkins:lts
        sudo mkdir /home/jenkins/.ssh
        sudo chmod 700 /home/jenkins/.ssh
        ssh-keygen -t rsa -f /home/jenkins/.ssh/id_rsa -P ''
        docker run --name spring-server -itd -p 9000:9000 -p 9022:22 jochanho/spring-server:latest
        sudo docker cp /home/jenkins/.ssh/id_rsa.pub spring-server:/home/spring/.ssh/authorized_keys
        
        SCRIPT
    end

    config.vm.define "spring" do |spring|
        spring.vm.hostname = "spring"
        spring.vm.provider "virtualbox" do |vb|
            vb.name = "spring"
            vb.cpus = 4
            vb.memory = 8192
        end
        spring.vm.network "private_network", ip: "192.168.10.13"
        spring.vm.network "public_network"
    end

end