apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-rolebinding
  namespace: default

#계정
subjects:
- apiGroups: ""
  kind: ServiceAccount
  name: user1

#권한
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: user1-role