Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "py" do |py|
        py.vm.hostname = "py-server"
        py.vm.provider "virtualbox" do |vb|
            vb.name = "py-server"
            vb.cpus = 4
            vb.memory = 4096
        end
    end

end